CREATE TABLE IF NOT EXISTS module(
    id INT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    direction VARCHAR(255) NOT NULL,
    is_available TINYINT(1) DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS page(
    id INT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    path VARCHAR(255) NOT NULL,
    FK_module INT NOT NULL,
    is_available TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT  CURRENT_TIMESTAMP,
    CONSTRAINT fk_module_page FOREIGN KEY (FK_module) REFERENCES module(id)
);